name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      run: mamba install python=${{ matrix.python-version }} pip nodejs flake8

    - name: Mamba install dependencies
      run: mamba install jupyterlab ipywidgets jupyter-packaging~=0.7.9

    - name: Install ipyleaflet
      run: pip install .

    - name: Import check
      run: python -c 'import dsvisualizer'
