name: Release

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      run: mamba install python nodejs releasewidgets notebook yarn twine jupyterlab=3 jupyter-packaging python-build

    - name: build dsvisualizer
      run: |
        python setup.py sdist
        python setup.py bdist_wheel

    - name: Publish js library
      uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: js/package.json

    - name: Publish Python package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
